version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-parking
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_db
      MYSQL_USER: parking
      MYSQL_PASSWORD: parking123
    volumes:
      - mysql_parking_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_parking_data:
